version: '3'
services:
  app:
    build: '.'
    environment:
      - VAULT_ADDR=https://vault.${DOMAIN}
      - VAULT_ROLE_ID=430c9ff4-6dde-c22e-3aa7-b91906854fad
      - VAULT_WRAPPED_SECRET_ID=${VAULT_WRAPPED_SECRET_ID}
    logging:
      driver: loki
      options:
        loki-url: https://logs.${DOMAIN}/loki/api/v1/push
        max-file: 2
        max-size: 200m
