version: '3'
services:
  app:
    restart: always
    image: linkbot:latest
    build: '.'
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_ROLE_ID=${VAULT_ROLE_ID}
      - VAULT_SECRET_ID=${VAULT_SECRET_ID}
