version: '3'
services:
  app:
    build: '.'
    restart: always
    logging:
      driver: loki
      options:
        loki-url: https://logs.teabee.dev/loki/api/v1/push
        max-file: 2
        max-size: 200m
