AWSTemplateFormatVersion: 2010-09-09

Resources:
  User: 
    Type: AWS::IAM::User
    Properties:
      UserName: link-bot
      Policies:
        - PolicyName: Inline
          PolicyDocument:
            Version: 2012-10-17
            Statement: 
              - Effect: Allow
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                Resource: 
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/app/linkbot
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/app/linkbot:log-stream:*
              - Effect: Allow
                Action: ssm:GetParameter*
                Resource: 
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mongodb/database/linkbot/prod
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/mongodb/user/tyler
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/discord/bot/link-bot
              - Effect: Allow
                Action: appconfig:GetConfiguration
                Resource: 
                  - !Sub arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/qj8a9hk
                  - !Sub arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/qj8a9hk/environment/navsfyu
                  - !Sub arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/qj8a9hk/configurationprofile/9nsh18t
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      Status: Active
      UserName: !Ref User
  AccessKeyParameter:
    Type: Custom::SecureStringParameter
    Properties:
      ServiceToken: !ImportValue cfn-custom-resource-secure-string-parameter
      Name: /linkbot/access-key
      Description: Access key for the linkbot user
      Value: !Sub '{"id":"${AccessKey}","secret":"${AccessKey.SecretAccessKey}"}'
