version: '3'
services:
  database:
    restart: always
    image: mongo:latest
    env_file:
      - ../.env
    volumes:
      - ./.database:/data/db
    logging:
      driver: loki
      options:
        loki-url: https://sys.teabee.dev/loki/api/v1/push
        max-file: 2
        max-size: 200m
  app:
    depends_on:
      - database
    restart: always
    build:
      context: '..'
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    logging:
      driver: loki
      options:
        loki-url: https://sys.teabee.dev/loki/api/v1/push
        max-file: 2
        max-size: 200m
