version: '3.6'
services:
  database:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER:?}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:?}
    volumes:
      - ./.database:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
  app:
    restart: always
    depends_on:
      database:
        condition: service_healthy
    image: cr.teabee.dev/tjbrockmeyer/linkbot-x:${IMAGE_TAG:?}
    environment:
      - MONGODB_URL=database
      - MONGODB_USER=${MONGODB_USER:?}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:?}
      - DISCORD_TOKEN=${DISCORD_TOKEN:?}
