version: '3'
services:
  database:
    image: mongo:latest
    env_file:
      - ../.env
    volumes:
      - ../.database:/data/db
  app:
    image: node:16
    restart: always
    depends_on:
      - database
    entrypoint: npm run dev
    working_dir: /app
    volumes:
      - ..:/app
    env_file:
      - ../.env
