name: Build Image
on:
  push:
    branches:
      - $default-branch
    paths:
      - src/**/*.ts
  workflow_dispatch:
env:
  ROLE: arn:aws:iam::060868188835:role/linkbot-github-runner-role
  ECR_REPO_NAME: linkbot
jobs:
  buildImage:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        region: [us-east-1]
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ matrix.region }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - id: shorten-sha
        run: |
          INPUT=${{ github.sha }}
          echo "::set-output name=sha::${INPUT:0:6}"
      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: dev-${{ steps.shorten-sha.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG"
