name: Lightsail Deploy
on:
  workflow_call:
  workflow_dispatch:
env:
  ROLE: arn:aws:iam::060868188835:role/linkbot-github-runner-role
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ inputs.region }}
      - name: Build Image
        run: |
          npm run docker:build
          

