name: Test PR
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - $default-branch
    paths:
      - src/**/*.ts
jobs:
  testAndBuild:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test:ci
      - run: npm run build
  dockerBuild:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t linkbot .
